export enum ApplicationErrors {
  UNKNWON_ERROR = "UNKNWON_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  LOAN_NOT_FOUND = "LOAN_NOT_FOUND",
  LOAN_ALREADY_EXISTS = "LOAN_ALREADY_EXISTS",
  MISMATCH_LOAN = "MISMATCH_LOAN",
  INVALID_LOAN_AMOUNT = "INVALID_LOAN_AMOUNT",
  INVALID_BILLING = "INVALID_BILLING",
  INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND",
  INVOICE_ALREADY_EXISTS = "INVOICE_ALREADY_EXISTS",
  UNAUTHORIZED = "UNAUTHORIZED",
  BAD_REQUEST = "BAD_REQUEDST",
}
